DROP TABLE IF EXISTS hits CASCADE;
CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app        VARCHAR(256),
    uri        VARCHAR(2048),
    ip         VARCHAR(45),
    timestamp TIMESTAMP WITH TIME ZONE
                             );